### ISSUE TITLE
running azk

### ISSUE THREAD

**Issue by stewartellis** [r3stack/r3stack#4]
New to AZK and just trying to get r3stack up and running. I've followed the instructions, and am getting the error below. Looks like rethinkdb isn't starting up. 

bash:

r3stack-master => $ azk start
azk: Skip starting, system `deploy` does not scale.
azk: ↑ starting `rethinkdb` system, 1 new instances...
azk: ✓ checking `library/rethinkdb:latest` image...
azk: ◴ waiting for `rethinkdb` system to start, trying connection to port http/tcp...
azk: An error occurred. It will stop all instances already running. See details below.

azk: System `r3stack` not running
azk: ↓ stopping `rethinkdb` system, 1 instances...
azk: Skip stoping, system `deploy` does not scale.
azk: Run system `rethinkdb` return: (0), for command: ["/bin/sh","-c","rethinkdb --bind all --direct-io --cache-size 2000 --server-name rethinkdb --directory ./rethinkdb --canonical-address rethinkdb.dev.azk.io"]:
azk: [timeout] `azk` has timed out on `rethinkdb` system.
azk: [timeout] Failure to reach port `8080` from `http://rethinkdb.dev.azk.io` after 20000 milliseconds.
azk: [timeout] Make sure the start command binds `port` to the `0.0.0.0` interface, not only to the `localhost` interface.
azk: [timeout] You might want to edit your `Azkfile.js` in order to increase the maximum timeout.

azk: Look for azk start troubleshooting documentation for more info at: http://bit.ly/azk_start_troubleshooting

azk: Sorry, an error has occurred.
azk: A crash report about this error will be sent to azk team in order to make azk better.
azk: Sending bug report to Azuki...
azk: Bug report was sent. Thanks.
r3stack-master => $

I did have meatier.io running previously (without AZK obviously).

Any help would be greatly appreciated. 
PS - really looking forward to working with r3stack - great effort!
Thanks

**Comment by Bartekus** [comment]
I'm sorry, I'll correct the README.md immediately since before running azk start, the usual npm install should still take place. Azk will sync the content of the node_modules folder thereafter and be able to boot as per usual. To get a better insight into whats happening during the start up you can execute start with verbose flag and also attach trailing log to capture return values that are usual silent, like this:
>azk start -vv && azk logs --follow

FYI, if you want to force azk to reinitialize the development just use word restart in place of start and it will restart the process instead of trying to take of from where it previously has stop. This can be useful in cases where there are changes to the node_modules or other structural changes.

**Comment by paralin** [comment]
Actually you shouldn't have to run `npm install` before.

`azk start --rebuild` should work fine.

I'm repairing some things in the repo as it seems some packages are required in prod but are under devDependencies.

**Comment by Bartekus** [comment]
Thank you @paralin , yeah a lot of this is still new so it's bound to have issue, but I'm sure with our combined efforts we will sort it all out. Please feel free to submit pull request once you're done and we'll gladly merge after some minor testing. Also being that you are one of the first few with extensive container experience, if you are fan of Aaron Swartz and would like to become part of Araphel group and by extension R3stack project please send me an email at bartekus ~at~ gmail ~dot~ com

**Comment by paralin** [comment]
Thanks @Bartekus, I sent you a note.

I have it working under azk. Just fixing some azk bugs actually on my end.

**Comment by Bartekus** [comment]
@stewartellis we're you able to overcome the problem that you we're facing? Please let us know as we wan't to hear from you before we close this issue!

**Comment by stewartellis** [comment]
@Bartekus  - no luck - still experiencing the same issue. I cloned the repo again, ran npm install and then:

r3stack => $ azk start -vv && azk logs --follow
azk: Skip starting, system `deploy` does not scale.
azk: ↑ starting `rethinkdb` system, 1 new instances...
azk: ✓ checking `library/rethinkdb:latest` image...
azk: ◴ waiting for `rethinkdb` system to start, trying connection to port http/tcp...
azk: An error occurred. It will stop all instances already running. See details below.

Recursively removing directory /data/rethinkdb/tmp
Initializing directory /data/rethinkdb
Running rethinkdb 2.2.5~0jessie (GCC 4.9.2)...
azk: System `r3stack` not running
Running on Linux 3.16.0-4-amd64 x86_64
Loading data from directory /data/rethinkdb
azk: ↓ stopping `rethinkdb` system, 1 instances...
azk: Skip stoping, system `deploy` does not scale.
azk: Run system `rethinkdb` return: (0), for command: ["/bin/sh","-c","rethinkdb --bind all --direct-io --cache-size 2000 --server-name rethinkdb --directory ./rethinkdb --canonical-address rethinkdb.dev.azk.io"]:
azk: [timeout] `azk` has timed out on `rethinkdb` system.
azk: [timeout] Failure to reach port `8080` from `http://rethinkdb.dev.azk.io` after 20000 milliseconds.
azk: [timeout] Make sure the start command binds `port` to the `0.0.0.0` interface, not only to the `localhost` interface.
azk: [timeout] You might want to edit your `Azkfile.js` in order to increase the maximum timeout.

azk: Look for azk start troubleshooting documentation for more info at: http://bit.ly/azk_start_troubleshooting

azk: Sorry, an error has occurred.
azk: A crash report about this error will be sent to azk team in order to make azk better.
azk: Sending bug report to Azuki...
azk: Bug report was sent. Thanks.
r3stack => $

Also, running npm install itself seems to have some issues. 

r3stack => $ npm install
....... after bringing down the packages:

[0] Creating a pool connected to rethinkdb.dev.azk.io:28015
[0] Entering slow growth mode
[0] Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to rethinkdb.dev.azk.io:28015\nFull error:\n{\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"192.168.50.4\",\"port\":28015}.","isOperational":true}
[0] Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to rethinkdb.dev.azk.io:28015\nFull 

I can provide the full bash output if helpful.

I already had rethinkdb on my machine, but I assume that's of no consequence if we're in a container.
Happy to help anyway I can.

Thanks again

**Comment by paralin** [comment]
It is of consequence because the docker system tries to port map the same port for rethinkdb.

Either edit Azkfile.js and change the rethinkdb port or stop your local rethinkdb instance and try again.

It shouldn't be like this but it is.

**Comment by Bartekus** [comment]
Indeed, I've attempted to keep the standard ports the same so that people could reuse the azkfile to run/stop rethinkdb since I'm not a fan of having the database startup with my machine, let alone use the same port as a lot of other developments do, in effect rendering them inoperable. However I could tweak it so that it's specific to azk instance only, this way it won't derail itself trying to use the same port as already installed instance of rethindb. Please give me few minutes to rectify this problem.

**Comment by paralin** [comment]
I would prefer to just not port map it at all and keep all the communication internal unless port mapped

**Comment by Bartekus** [comment]
ok I haven't done full test, so I hope it wont explode, but yeah, @paralin we think alike, as that's what I've done here. I'm going to purge r3stack from my system and do clean install to see if it works smoothly.

**Comment by stewartellis** [comment]
This issue occurs even when rethinkdb is not set to run at start up? I was just looking around the activity monitor for the rethinkdb process and could not see anything. Also, as far as I remember, I didn't go through this process - https://rethinkdb.com/docs/start-on-startup/ to configure to run at start up.

**Comment by Bartekus** [comment]
@stewartellis try to erase the whole r3stack folder, and clone fresh version then do:
`azk start -vv && azk logs --follow`

Also no npm install or anything like that, just azk this time. Let us know what you get.

**Comment by stewartellis** [comment]
@Bartekus  - just gave it a try. Still no luck...

r3stack => $ azk start -vv && azk logs --follow
azk: Skip starting, system `deploy` does not scale.
azk: ↑ starting `rethinkdb` system, 1 new instances...
azk: ✓ checking `library/rethinkdb:latest` image...
azk: ◴ waiting for `rethinkdb` system to start, trying connection to port http/tcp...
azk: An error occurred. It will stop all instances already running. See details below.

azk: System `r3stack` not running
azk: ↓ stopping `rethinkdb` system, 1 instances...
azk: Skip stoping, system `deploy` does not scale.
azk: Run system `rethinkdb` return: (0), for command: ["/bin/sh","-c","rethinkdb --bind all --direct-io --cache-size 2000 --server-name rethinkdb --directory ./rethinkdb --canonical-address rethinkdb.dev.azk.io"]:
azk: [timeout] `azk` has timed out on `rethinkdb` system.
azk: [timeout] Failure to reach port `32773` from `http://rethinkdb.dev.azk.io` after 20000 milliseconds.
azk: [timeout] Make sure the start command binds `port` to the `0.0.0.0` interface, not only to the `localhost` interface.
azk: [timeout] You might want to edit your `Azkfile.js` in order to increase the maximum timeout.

azk: Look for azk start troubleshooting documentation for more info at: http://bit.ly/azk_start_troubleshooting

azk: Sorry, an error has occurred.
azk: A crash report about this error will be sent to azk team in order to make azk better.
azk: Sending bug report to Azuki...
azk: Bug report was sent. Thanks.
r3stack => $


... should it be trying to start rethinkdb before all the npm modules have been brought down?

**Comment by Bartekus** [comment]
try to increase "timeout" under rethinkdb from 10000 to something like 50000, then see if you can start just the rethinkdb by:
`azk start rethinkdb -vv && azk logs --follow`

**Comment by stewartellis** [comment]
That worked. 

I stopped it and then ran azk start -vv && azk logs --follow  - which also appears to be working, although the lodash npm package does not want to come down at the moment. Probably some network connectivity issue. I'll confirm once the install is complete.

**Comment by Bartekus** [comment]
ok, keep us posted, I think we might have more issues coming our way since graphql is tied into all of this as well so I'm working on straightening this out as on my end I'm now experiencing what @veenified has reported.

**Comment by paralin** [comment]
All of this works fine for me which is quite odd as it should be reproduceable no matter what environment it's in...

**Comment by Bartekus** [comment]
indeed, my setup work like a charm, but trying to access http://r3stack.dev.azk.io it times out... I'm looking into my machines to see if it's dns, arp tables or whatnot, but it's peculiar I must say.

**Comment by paralin** [comment]
Oh I have that problem as well, the server never responds to the request.

**Comment by Bartekus** [comment]
I alleviated the issue temporarily by switching to dev environment instead of production, it seems to me that there is some tanglement between production/development but I'm not done investigating therefore I cannot say with certainty.

**Comment by veenified** [comment]
I am getting the following when running `azk shell r3stack -v -- npm run dev`:
```
$ azk shell r3stack -v -- npm run dev
npm info it worked if it ends with ok
npm info using npm@3.3.12
npm info using node@v5.2.0
npm info lifecycle r3stack@0.11.0~predev: r3stack@0.11.0
npm info lifecycle r3stack@0.11.0~dev: r3stack@0.11.0

> r3stack@0.11.0 dev /azk/r3stack
> NODE_ENV=development npm start

npm info it worked if it ends with ok
npm info using npm@3.3.12
npm info using node@v5.2.0
npm info lifecycle r3stack@0.11.0~prestart: r3stack@0.11.0
npm info lifecycle r3stack@0.11.0~start: r3stack@0.11.0

> r3stack@0.11.0 start /azk/r3stack
> node ./src/server/server.babel.js

   [Busy] Launching SocketCluster
   >> Broker PID: 43
1456924915886 - Origin: Broker (PID 43)
   [Error] Error: listen EPERM /azk/r3stack/socketcluster/Meatier_2caa0e5a08/b0
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1225:19)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1364:5)
    at EventEmitter.self.listen (/azk/r3stack/node_modules/ncom/index.js:139:19)
    at Object.<anonymous> (/azk/r3stack/node_modules/sc-broker/server.js:502:10)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
```

What method are you, @Bartekus, using to work in dev mode?

**Comment by Bartekus** [comment]
I would remove any previous version/folder of r3stack, then clone a fresh version from the repo and just start it normally using `azk start -vv`

The error you are getting might be fixed by:
`azk shell r3stack -- rm -rf build socketcluster`
then:
`azk shell r3stack -- npm run reset`
afterwards:
`azk restart -vv`

So try one of these two methods and let us know how it goes. I'll be working on fixing the production.

**Comment by veenified** [comment]
Pulling a fresh clone of the repo worked. Thanks @Bartekus

**Comment by Bartekus** [comment]
Excellent, FYI the full fix is not yet in place @veenified, if you look into the Azkfile.js, you'll find this line:
`command: ["npm", "run", "dev"],`
this means that currently the build is executed in development and if you look at r3stack.com (deployed in development mode, OMG, such a no-no, but for now, it's better to have something up than nothing) you might notice that kanban wont work properly, although in your local development it will. Just something to keep in mind. 

@stewartellis if you re-pull the build it should work now as it's being executed in dev. 

I'll try to fix the production as soon as I can.

**Comment by Bartekus** [comment]
I've fixed the production altho I'm not yet fully satisfied with it... However it should work within full capacity locally now so please give it a go.

**Comment by Bartekus** [comment]
Closing as it should be all good now.

**Comment by stewartellis** [comment]
Hey @Bartekus, I've been been away for a few weeks and have not had a chance to take another stab at this until now. Still no dice for me.

When I clone the repo and run the azk command it looks like things start but it never pulls down the npm packages. When I run the rebuild command it errors out and does the whole crash report to the azk team thing. After running both commands I still have an empty npm_modules folder. 

Having said all that, I saw the question regarding meatier vs r3stack. As I did not know about AZK before this port from meatier and am really just interested in the the three Rs themselves, I think I'll go back to working with meatier. Thanks for all your efforts in trying to help. 

cheers
